FROM nginx:alpine

# Copy static files
COPY alpine/ /usr/share/nginx/html/
COPY env.prod.js /usr/share/nginx/html/env.js

# Nginx configuration
RUN rm -f /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
