FROM nginx:alpine

# Copy static files
COPY alpine/ /usr/share/nginx/html/

# Nginx configuration
RUN rm -f /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
