# Define conversation states
ENTER_TRANSACTION, ACCOUNT_SELECTION, SELECT_TYPE, SELECT_CATEGORY, ENTER_AMOUNT, SELECT_PERIOD, VIEW_PERIOD, ENTER_ACCOUNT_NAME, ENTER_ACCOUNT_AMOUNT = range(9)

# UI constants
CATEGORIES_PER_ROW = 3

